In [3]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [4]:
df = pd.read_csv("/content/Dataset of Diabetes .csv")

In [5]:
df.head()

    ID  No_Pation Gender  AGE  Urea  Cr  ...   TG  HDL  LDL  VLDL   BMI  CLASS
0  502      17975      F   50   4.7  46  ...  0.9  2.4  1.4   0.5  24.0      N
1  735      34221      M   26   4.5  62  ...  1.4  1.1  2.1   0.6  23.0      N
2  420      47975      F   50   4.7  46  ...  0.9  2.4  1.4   0.5  24.0      N
3  680      87656      F   50   4.7  46  ...  0.9  2.4  1.4   0.5  24.0      N
4  504      34223      M   33   7.1  46  ...  1.0  0.8  2.0   0.4  21.0      N

[5 rows x 14 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   float64
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   float64
dtypes: float64(10), int64(4)
memory usage: 109.5 KB

In [28]:
df['HbA1c'].value_counts()

HbA1c
8.00     34
7.00     32
9.00     32
6.80     30
4.00     30
         ..
14.40     1
14.10     1
16.00     1
13.30     1
9.96      1
Name: count, Length: 111, dtype: int64

In [19]:
print(df.isnull().sum()[df.isnull().sum()>0])

Series([], dtype: int64)

In [23]:
cat_cols = df.select_dtypes(include=['object']).columns
print(cat_cols)

Index([], dtype='object')

In [24]:
encoder = OrdinalEncoder()
df[cat_cols] = encoder.fit_transform(df[cat_cols])
df.head()

    ID  No_Pation  Gender  AGE  Urea  Cr  ...   TG  HDL  LDL  VLDL   BMI  CLASS
0  502      17975     0.0   50   4.7  46  ...  0.9  2.4  1.4   0.5  24.0    0.0
1  735      34221     1.0   26   4.5  62  ...  1.4  1.1  2.1   0.6  23.0    0.0
2  420      47975     0.0   50   4.7  46  ...  0.9  2.4  1.4   0.5  24.0    0.0
3  680      87656     0.0   50   4.7  46  ...  0.9  2.4  1.4   0.5  24.0    0.0
4  504      34223     1.0   33   7.1  46  ...  1.0  0.8  2.0   0.4  21.0    0.0

[5 rows x 14 columns]

In [21]:
numer_cols = df.select_dtypes(include = ['float64', 'int64']).columns
print(numer_cols)

Index(['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG',
       'HDL', 'LDL', 'VLDL', 'BMI', 'CLASS'],
      dtype='object')

In [26]:
imputer = SimpleImputer(strategy='mean')
df[numer_cols] = imputer.fit_transform(df[numer_cols])
df.head()

      ID  No_Pation  Gender   AGE  Urea    Cr  ...   TG  HDL  LDL  VLDL   BMI  CLASS
0  502.0    17975.0     0.0  50.0   4.7  46.0  ...  0.9  2.4  1.4   0.5  24.0    0.0
1  735.0    34221.0     1.0  26.0   4.5  62.0  ...  1.4  1.1  2.1   0.6  23.0    0.0
2  420.0    47975.0     0.0  50.0   4.7  46.0  ...  0.9  2.4  1.4   0.5  24.0    0.0
3  680.0    87656.0     0.0  50.0   4.7  46.0  ...  0.9  2.4  1.4   0.5  24.0    0.0
4  504.0    34223.0     1.0  33.0   7.1  46.0  ...  1.0  0.8  2.0   0.4  21.0    0.0

[5 rows x 14 columns]